# Migration Script: Add MonthlyService Table
# Run this command in terminal: flask db migrate -m "add MonthlyService table"

"""add MonthlyService table

Revision ID: add_monthly_service
Create Date: 2025-11-01

"""

# revision identifiers
revision = 'add_monthly_service'
down_revision = None  # Replace with previous migration ID
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('has_english', sa.Boolean(), nullable=False),
    sa.Column('has_steamax', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'month', name='unique_child_month')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_service')
    # ### end Alembic commands ###