"""add email phone password to child and staff

Revision ID: 5f2a664a4e6a
Revises: 8d3e5928080b
Create Date: 2025-07-18 17:29:27.868367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2a664a4e6a'
down_revision = '8d3e5928080b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('child', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('child', sa.Column('password', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('staff', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password')
    op.drop_column('staff', 'phone')
    op.drop_column('staff', 'email')
    op.drop_column('child', 'password')
    op.drop_column('child', 'phone')
    op.drop_column('child', 'email')
    # ### end Alembic commands ###
