"""add image to activity

Revision ID: e17407d6254c
Revises: 5f2a664a4e6a
Create Date: 2025-07-18 19:58:56.027098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17407d6254c'
down_revision = '5f2a664a4e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('student_code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'child', ['student_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child', type_='unique')
    op.drop_column('child', 'student_code')
    # ### end Alembic commands ###
