"""auto migration

Revision ID: e78089248be0
Revises: e47f137c4b5f
Create Date: 2025-08-23 17:43:41.430517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e78089248be0'
down_revision = 'e47f137c4b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('meal_times', sa.JSON(), nullable=True))
    op.drop_column('dish_ingredient', 'meal_times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_ingredient', sa.Column('meal_times', sqlite.JSON(), nullable=True))
    op.drop_column('dish', 'meal_times')
    # ### end Alembic commands ###
