"""Add student album and progress tracking tables

Revision ID: student_album_001
Revises: 7ac5a2b83144
Create Date: 2025-08-18 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'student_album_001'
down_revision = '7ac5a2b83144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=False),
    sa.Column('milestone_type', sa.String(length=50), nullable=True),
    sa.Column('school_year', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('age_at_time', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('is_shared_with_parents', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('skill_category', sa.String(length=50), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('level_achieved', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('filepath', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('image_order', sa.Integer(), nullable=True),
    sa.Column('is_cover_photo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['student_album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_photo')
    op.drop_table('student_progress')
    op.drop_table('student_album')
    # ### end Alembic commands ###
